version: "3.9"

include:
  - .eadkp/docker-compose.base.yml

services:
  eadkp-dev:
    volumes:
      - ./:/workspace/${PROJECT_NAME}
      - 'c 189:* rmw'   # All USB devices (major 189)
      - 'c 166:* rmw'   # ttyACM devices (kernel-dependent / not always required)
      - 'c 204:* rmw'   # ttyAMA or alternatives (kernel-dependent)

# X11 and Wayland support (on Linux hosts).
# For Windows/WSL2, WSL2 integrate a X server
# For macOS, you likely need an external X11 server and manual socket setup. (untested)