name: Rust CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EADKP_PRIMARY_BUILD: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ARM Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi libnewlib-arm-none-eabi

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: thumbv7em-none-eabihf

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Extract project name
        id: proj
        run: |
          NAME=$(just --evaluate | awk '/^project_name/ { print $3 }' | tr -d '"')
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Build and Export NWA and check Linux simulator compilation
        run: |
          just export
          just build_simulator
          ls -lah build/

      - name: Upload NWA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.proj.outputs.name }}.nwa
          path: build/${{ steps.proj.outputs.name }}.nwa

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Extract project name
        id: proj
        run: |
          NAME=$(just --evaluate | awk '/^project_name/ { print $3 }' | tr -d '"')
          echo "name=$NAME" >> $GITHUB_OUTPUT

      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: build/
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/${{ steps.proj.outputs.name }}.nwa
          generate_release_notes: true
          draft: false
          prerelease: false
